name: one_kilo_amount
description: "A new Flutter project."
publish_to: 'none'
version: 1.1.1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
